create table if not exists public.uptime_targets (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  url text not null,
  added_by text not null,
  added_at timestamptz not null default timezone('utc', now()),
  last_checked_at timestamptz,
  last_status integer,
  last_response_ms integer,
  is_up boolean
);

create unique index if not exists uptime_targets_guild_url_idx
  on public.uptime_targets (guild_id, url);

alter table public.uptime_targets enable row level security;
